language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zlib1g-dev libboost-dev libsparsehash-dev
script:
  - ./autogen.sh
  - ./configure
  - make
